USE venhawk;

INSERT INTO vendors (
  vendor_id,
  brand_name,
  legal_name,
  website_url,
  logo_url,
  listing_order,
  listing_description,
  listing_specialty,
  listing_tier,
  hq_country,
  company_size_band,
  founded_year,
  vendor_type,
  engagement_models,
  service_domains,
  platforms_experience,
  legal_tech_stack,
  lead_time_weeks,
  capacity_band,
  min_project_size_usd,
  max_project_size_usd,
  typical_duration_weeks_min,
  typical_duration_weeks_max,
  pricing_signal_notes,
  case_study_count_public,
  reference_available,
  rating_source_1,
  rating_1,
  review_count_1,
  legal_focus_level,
  has_soc2,
  has_iso27001,
  data_owner,
  data_source_notes,
  last_verified_date,
  status
) VALUES
(
  'dff94198-9f09-4e32-934a-d367d5eb9af7',
  'Ernst & Young',
  'Ernst & Young Global Limited',
  'https://www.ey.com',
  'https://logo.clearbit.com/ey.com',
  1,
  'Elktech is a software solution company that provides software solutions in the field of AI & Saas.',
  'Fintech',
  'Tier 1',
  'United Kingdom',
  '10000+',
  1989,
  'Finance & Accounting',
  'Implementation; Advisory',
  'Finance, Accounting',
  'SAP, Oracle',
  'SAP, Oracle',
  4,
  'Large',
  50000.00,
  600000.00,
  4,
  24,
  'Dummy listing vendor for procurement page',
  2,
  'Y',
  'Internal',
  4.5,
  128,
  'Strong',
  'Y',
  'Y',
  'Product Team',
  'Seeded for procurement listing UI',
  CURRENT_DATE(),
  'Active'
),
(
  'be8ab7ca-8cf9-41e1-a031-d9c75f6345f8',
  'PricewaterhouseCoopers (PwC)',
  'PricewaterhouseCoopers International Limited',
  'https://www.pwc.com',
  'https://logo.clearbit.com/pwc.com',
  2,
  'PricewaterhouseCoopers International Limited is a British multinational professional services brand of firms, operating as partnerships under the PwC brand.',
  'Accounting',
  'Tier 1',
  'United Kingdom',
  '10000+',
  1998,
  'Business Solutions',
  'Implementation; Advisory',
  'Accounting, Audit',
  'SAP, Workday',
  'SAP, Workday',
  4,
  'Large',
  50000.00,
  700000.00,
  6,
  24,
  'Dummy listing vendor for procurement page',
  2,
  'Y',
  'Internal',
  4.5,
  96,
  'Strong',
  'Y',
  'Y',
  'Product Team',
  'Seeded for procurement listing UI',
  CURRENT_DATE(),
  'Active'
),
(
  '9ebe8dd2-b6ec-4f65-99f1-3048fdb6f9e0',
  'Accenture',
  'Accenture plc',
  'https://www.accenture.com',
  'https://logo.clearbit.com/accenture.com',
  3,
  'Accenture plc is an American multinational professional services company headquartered in Dublin for tax reasons, specializing in information technology services and consulting.',
  'Development',
  'Tier 1',
  'United States',
  '10000+',
  1989,
  'Software & IT',
  'Implementation; Advisory',
  'Software, IT',
  'Cloud, Integration',
  'Azure, AWS',
  3,
  'Large',
  50000.00,
  900000.00,
  6,
  26,
  'Dummy listing vendor for procurement page',
  2,
  'Y',
  'Internal',
  4.5,
  110,
  'Strong',
  'Y',
  'Y',
  'Product Team',
  'Seeded for procurement listing UI',
  CURRENT_DATE(),
  'Active'
),
(
  '65fe96d7-315f-4c4f-a046-a9d48f7bb56d',
  'Slalom',
  'Slalom Consulting',
  'https://www.slalom.com',
  'https://logo.clearbit.com/slalom.com',
  4,
  'Slalom is a business and technology consulting firm headquartered in Seattle, Washington.',
  'Finance',
  'Tier 2',
  'United States',
  '1000+',
  2001,
  'Business Solutions',
  'Implementation; Advisory',
  'Business, Strategy',
  'Cloud, Data',
  'Azure, Snowflake',
  3,
  'Med',
  25000.00,
  500000.00,
  6,
  20,
  'Dummy listing vendor for procurement page',
  1,
  'Y',
  'Internal',
  4.5,
  52,
  'Some',
  'Y',
  'Y',
  'Product Team',
  'Seeded for procurement listing UI',
  CURRENT_DATE(),
  'Active'
),
(
  '86593b74-3f79-4c83-b484-8813f8f3d760',
  'Dynatrace',
  'Dynatrace LLC',
  'https://www.dynatrace.com',
  'https://logo.clearbit.com/dynatrace.com',
  5,
  'Dynatrace''s software platform combines observability, business and security data at scale to capture and retain full-stack context.',
  'Fintech',
  'Tier 3',
  'United Kingdom',
  '100-500',
  2005,
  'Software Solutions',
  'Implementation; Advisory',
  'Monitoring, Security',
  'Observability, AIOps',
  'Kubernetes, OpenTelemetry',
  2,
  'Small',
  15000.00,
  250000.00,
  4,
  16,
  'Dummy listing vendor for procurement page',
  1,
  'Y',
  'Internal',
  4.5,
  44,
  'Some',
  'Y',
  'Y',
  'Product Team',
  'Seeded for procurement listing UI',
  CURRENT_DATE(),
  'Active'
),
(
  '3d11b0ec-e51d-4a25-9d6f-41c56566ce7c',
  'Smartly',
  'Smartly.io Solutions Oy',
  'https://www.smartly.io',
  'https://logo.clearbit.com/smartly.io',
  6,
  'Smartly, trusted by brands like Uber and eBay, is an AI-powered marketing technology company specializing in social media advertising.',
  'Fintech',
  'Tier 3',
  'United Kingdom',
  '100-500',
  2013,
  'Software Solutions',
  'Implementation; Advisory',
  'Marketing, Automation',
  'Automation, Advertising',
  'Meta Ads, TikTok Ads',
  2,
  'Small',
  15000.00,
  250000.00,
  4,
  16,
  'Dummy listing vendor for procurement page',
  1,
  'Y',
  'Internal',
  4.5,
  38,
  'Some',
  'Y',
  'Y',
  'Product Team',
  'Seeded for procurement listing UI',
  CURRENT_DATE(),
  'Active'
)
ON DUPLICATE KEY UPDATE
  brand_name = VALUES(brand_name),
  legal_name = VALUES(legal_name),
  website_url = VALUES(website_url),
  logo_url = VALUES(logo_url),
  listing_order = VALUES(listing_order),
  listing_description = VALUES(listing_description),
  listing_specialty = VALUES(listing_specialty),
  listing_tier = VALUES(listing_tier),
  hq_country = VALUES(hq_country),
  company_size_band = VALUES(company_size_band),
  founded_year = VALUES(founded_year),
  vendor_type = VALUES(vendor_type),
  engagement_models = VALUES(engagement_models),
  service_domains = VALUES(service_domains),
  platforms_experience = VALUES(platforms_experience),
  legal_tech_stack = VALUES(legal_tech_stack),
  lead_time_weeks = VALUES(lead_time_weeks),
  capacity_band = VALUES(capacity_band),
  min_project_size_usd = VALUES(min_project_size_usd),
  max_project_size_usd = VALUES(max_project_size_usd),
  typical_duration_weeks_min = VALUES(typical_duration_weeks_min),
  typical_duration_weeks_max = VALUES(typical_duration_weeks_max),
  pricing_signal_notes = VALUES(pricing_signal_notes),
  case_study_count_public = VALUES(case_study_count_public),
  reference_available = VALUES(reference_available),
  rating_source_1 = VALUES(rating_source_1),
  rating_1 = VALUES(rating_1),
  review_count_1 = VALUES(review_count_1),
  legal_focus_level = VALUES(legal_focus_level),
  has_soc2 = VALUES(has_soc2),
  has_iso27001 = VALUES(has_iso27001),
  data_owner = VALUES(data_owner),
  data_source_notes = VALUES(data_source_notes),
  last_verified_date = VALUES(last_verified_date),
  status = VALUES(status);
